version: 1.0.{build}
build:
  verbosity: minimal
environment:
  matrix:
    - GENERATOR: "Visual Studio 16 2019"
      CONFIGURATION: Debug
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - GENERATOR: "Visual Studio 16 2019 Win64"
      CONFIGURATION: Debug
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
	- GENERATOR: "Visual Studio 16 2019"
      CONFIGURATION: Release
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"
    - GENERATOR: "Visual Studio 16 2019 Win64"
      CONFIGURATION: Release
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2019"