version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2019
configuration:
- Debug
- Release
platform:
- Win32
- x64
shallow_clone: true
build:
  verbosity: normal
after_build:
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" src\vcpp\cardboard.nsi'
for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  artifacts:
  - path: src/vcpp/crimson_alpha_win_setup.exe
    name: Install
-
  matrix:
    only:
      - image: Ubuntu1804
        configuration: Release
        platform: x64

  build_script:
  - sh: cd src && chmod +x ./enet/check_cflags.sh && sudo apt update && sudo apt -y install libcurl4-openssl-dev libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev && make && make install
