version: 1.0.{build}
image:
- Visual Studio 2019
- Ubuntu1804
configuration:
- Release
platform:
- x64
shallow_clone: true
build:
  verbosity: normal
for:
-
  matrix:
    only:
      - image: Visual Studio 2019
        APPVEYOR_REPO_TAG: true

  after_build:
  - cmd: >-
      curl -L https://github.com/RRUZ/vcl-styles-plugins/releases/download/1.5.4.1/NSISVCLStyles.exe -o NSISVCLStyles.exe

      NSISVCLStyles.exe /S

      "C:\Program Files (x86)\NSIS\makensis.exe" src\vcpp\cardboard.nsi

  artifacts:
  - path: src/vcpp/crimson_alpha_win_setup.exe
  
-
  matrix:
    only:
      - image: Ubuntu1804

  build_script:
  - sh: cd src && chmod +x ./enet/check_cflags.sh && sudo apt-get update && sudo apt-get -y install libcurl4-openssl-dev libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev && make && make install
