version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x86
- x64
shallow_clone: true
build:
  verbosity: normal
after_build:
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" src\vcpp\cardboard.nsi'
artifacts:
- path: src/vcpp/crimson_alpha_win_setup.exe
  name: Install
for:
-
  matrix:
    only:
      - image: Ubuntu1804

  build_script:
  - echo Ubuntu build script test
