name: Continous integration for Project Crimson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build for Windows
        working-directory: ./src/vcpp
        run: msbuild /p:PlatformToolset=v142 /property:Platform=x64 cardboard.sln
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install C and C++ header files
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev libcurl4-openssl-dev
      - name: Fix enet permissions
        working-directory: ./src/enet
        run: chmod +x ./check_cflags.sh
      - name: Build for Ubuntu
        working-directory: ./src
        run: make
